### ISSUE TITLE
disk issue

### ISSUE THREAD

**Issue by MurphySongAI** [iantbutler01/rwkv-raven-qlora-4bit-instruct#1]
when i run main.py in my cloud service, it will download too many huge files over 50G in /home/.cache/huggingface/..., so that it's not work because i don't have enough space for that. Why it will download such a huge thing? And how to salve this problem? And where are these files download in?

**Comment by iantbutler01** [comment]
That's the rwkv-14bn model it's downloading, these models are big on disk. You'll need at least 100GB on disk to properly handle it, nothing I can do here really.

**Comment by iantbutler01** [comment]
I'm going to close this issue as its not really an issue with this reproduction, these models are just very big :/
